apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: eks-argo-frontend
  newName: 430963847993.dkr.ecr.us-west-2.amazonaws.com/qt-practical-devops-ecr-frontend
  newTag: "1"
- name: 430963847993.dkr.ecr.us-west-2.amazonaws.com/qt-practical-devops-ecr-frontend
  newTag: "2"
resources:
- _deployment.yaml
- _service.yaml
